### ISSUE TITLE
Use of undefined constant

### ISSUE THREAD

**Issue by ahmed-sigmalux** [littlebizzy/index-autoload#1]
Seeing this in my debug log:

`PHP Notice:  Use of undefined constant IDXAUTOLOAD_SCHEDULE - assumed 'IDXAUTOLOAD_SCHEDULE' in /var/www/wordpress/wp-content/plugins/index-autoload-littlebizzy/index-autoload.php on line 33`

**Comment by jessuppi** [comment]
Hmm, you didn't define `IDXAUTOLOAD_SCHEDULE` but seeing this, correct?

**Comment by ahmed-sigmalux** [comment]
Correct.

**Comment by ahmed-sigmalux** [comment]
We can't disable the plugin, too, because of the undefined constant.

**Comment by jessuppi** [comment]
What is your server config and PHP version? Are you using PHP 7.1 by chance?

**Comment by ahmed-sigmalux** [comment]
Yes, PHP-FPM 7.1 behind Nginx.

**Comment by jessuppi** [comment]
Okay, all of our plugins are coded for PHP 7.0 only at this time.

**Comment by ahmed-sigmalux** [comment]
I had to manually delete the plugin since it wouldn't uninstall. How do I remove the leftover cron job?

**Comment by jessuppi** [comment]
https://www.google.com/search?q=manage+wp+cron+jobs

**Comment by ahmed-sigmalux** [comment]
That's unnecessarily rude.
